# Generated by Django 4.1.2 on 2023-06-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='activo',
            new_name='cantidad',
        ),
    ]
